# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
import re


class Ui_MainWindow(object):
    resAnterior = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 431, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color:rgb(255, 255, 255);\n"
                                 "font: 28pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.uno = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("1"))
        self.uno.setGeometry(QtCore.QRect(20, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.uno.setFont(font)
        self.uno.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "\n"
                               "border-radius: 30px;")
        self.uno.setObjectName("uno")
        self.cinco = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("5"))
        self.cinco.setGeometry(QtCore.QRect(110, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cinco.setFont(font)
        self.cinco.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.cinco.setObjectName("cinco")
        self.tres = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("3"))
        self.tres.setGeometry(QtCore.QRect(200, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tres.setFont(font)
        self.tres.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.tres.setObjectName("tres")
        self.seis = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("6"))
        self.seis.setGeometry(QtCore.QRect(200, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seis.setFont(font)
        self.seis.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.seis.setObjectName("seis")
        self.dos = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("2"))
        self.dos.setGeometry(QtCore.QRect(110, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dos.setFont(font)
        self.dos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "\n"
                               "border-radius: 30px;")
        self.dos.setObjectName("dos")
        self.siete = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("7"))
        self.siete.setGeometry(QtCore.QRect(20, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.siete.setFont(font)
        self.siete.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.siete.setObjectName("siete")
        self.cuatro = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("4"))
        self.cuatro.setGeometry(QtCore.QRect(20, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cuatro.setFont(font)
        self.cuatro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                  "\n"
                                  "border-radius: 30px;")
        self.cuatro.setObjectName("cuatro")
        self.cero = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("0"))
        self.cero.setGeometry(QtCore.QRect(20, 460, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cero.setFont(font)
        self.cero.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.cero.setObjectName("cero")
        self.ocho = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("8"))
        self.ocho.setGeometry(QtCore.QRect(110, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ocho.setFont(font)
        self.ocho.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.ocho.setObjectName("ocho")
        self.nueve = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("9"))
        self.nueve.setGeometry(QtCore.QRect(200, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nueve.setFont(font)
        self.nueve.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.nueve.setObjectName("nueve")
        self.masmenos = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.mas_menos())
        self.masmenos.setGeometry(QtCore.QRect(200, 460, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.masmenos.setFont(font)
        self.masmenos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "\n"
                                    "border-radius: 30px;")
        self.masmenos.setObjectName("masmenos")
        self.punto = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.agregar_punto())
        self.punto.setGeometry(QtCore.QRect(110, 460, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.punto.setFont(font)
        self.punto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.punto.setObjectName("punto")
        self.limpiar = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.borrar_todo())
        self.limpiar.setGeometry(QtCore.QRect(390, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.limpiar.setFont(font)
        self.limpiar.setStyleSheet("background-color: rgb(255, 60, 34);\n"
                                   "\n"
                                   "border-radius: 30px;")
        self.limpiar.setObjectName("limpiar")
        self.parentesis_izq = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("("))
        self.parentesis_izq.setGeometry(QtCore.QRect(290, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.parentesis_izq.setFont(font)
        self.parentesis_izq.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                          "\n"
                                          "border-radius: 30px;")
        self.parentesis_izq.setObjectName("parentesis_izq")
        self.igual = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.calcular())
        self.igual.setGeometry(QtCore.QRect(390, 470, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.igual.setFont(font)
        self.igual.setStyleSheet("background-color: rgb(24, 255, 170);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.igual.setObjectName("igual")
        self.mas = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("+"))
        self.mas.setGeometry(QtCore.QRect(390, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mas.setFont(font)
        self.mas.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                               "\n"
                               "border-radius: 30px;")
        self.mas.setObjectName("mas")
        self.resta = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("-"))
        self.resta.setGeometry(QtCore.QRect(300, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resta.setFont(font)
        self.resta.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.resta.setObjectName("resta")
        self.multi = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("*"))
        self.multi.setGeometry(QtCore.QRect(300, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.multi.setFont(font)
        self.multi.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                 "\n"
                                 "border-radius: 30px;")
        self.multi.setObjectName("multi")
        self.divi = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("/"))
        self.divi.setGeometry(QtCore.QRect(390, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.divi.setFont(font)
        self.divi.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.divi.setObjectName("divi")
        self.ans = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado(self.resAnterior))
        self.ans.setGeometry(QtCore.QRect(300, 470, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ans.setFont(font)
        self.ans.setStyleSheet("background-color: rgb(3, 170, 8);\n"
                               "border-radius: 30px;")
        self.ans.setObjectName("ans")
        self.seno = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("sen("))
        self.seno.setGeometry(QtCore.QRect(20, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seno.setFont(font)
        self.seno.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                "\n"
                                "border-radius: 30px;")
        self.seno.setObjectName("seno")
        self.coseno = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("cos("))
        self.coseno.setGeometry(QtCore.QRect(110, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.coseno.setFont(font)
        self.coseno.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                                  "\n"
                                  "border-radius: 30px;")
        self.coseno.setObjectName("coseno")
        self.tangente = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado("tan("))
        self.tangente.setGeometry(QtCore.QRect(200, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tangente.setFont(font)
        self.tangente.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                    "\n"
                                    "border-radius: 30px;")
        self.tangente.setObjectName("tangente")
        self.borrar = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.borrar_ultimo())
        self.borrar.setGeometry(QtCore.QRect(300, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.borrar.setFont(font)
        self.borrar.setStyleSheet("background-color: rgb(255, 60, 34);\n"
                                  "\n"
                                  "border-radius: 30px;")
        self.borrar.setObjectName("borrar")
        self.parentesis_der = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.boton_presionado(")"))
        self.parentesis_der.setGeometry(QtCore.QRect(380, 120, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.parentesis_der.setFont(font)
        self.parentesis_der.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                          "\n"
                                          "border-radius: 30px;")
        self.parentesis_der.setObjectName("parentesis_der")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # ------------------- Funciones Calculadora -------------------

    def boton_presionado(self, pressed):
        if self.label.text() == "0" or self.label.text() == "0.0":
            self.label.setText("")
        self.label.setText(f'{self.label.text()}{pressed}')

    def borrar_todo(self):
        self.label.setText("0")

    def borrar_ultimo(self):
        pantalla = self.label.text()
        pantalla = pantalla[:-1]
        self.label.setText(pantalla)

    def agregar_punto(self):
        pantalla = self.label.text()
        if pantalla[-1] == ".":
            pass
        else:
            self.label.setText(f'{pantalla}.')

    def mas_menos(self):
        pantalla = self.label.text()
        if "-" in pantalla:
            self.label.setText(pantalla.replace("-", ""))
        else:
            self.label.setText(f'-{pantalla}')

    def calcular(self):
        pantalla = self.label.text()
        try:
            while "sen" in pantalla:
                numeros = re.findall(r'sen\((.*?)\)', pantalla)
                resultado = self.calc_trig(numeros[0], "sen")
                pantalla = re.sub(r'sen\(\d+(\.\d+)?\)', str(resultado), pantalla, 1)

            while "cos" in pantalla:
                numeros = re.findall(r'cos\((.*?)\)', pantalla)
                resultado = self.calc_trig(numeros[0], "cos")
                pantalla = re.sub(r'cos\(\d+(\.\d+)?\)', str(resultado), pantalla, 1)

            while "tan" in pantalla:
                numeros = re.findall(r'tan\((.*?)\)', pantalla)
                resultado = self.calc_trig(numeros[0], "tan")
                pantalla = re.sub(r'tan\(\d+(\.\d+)?\)', str(resultado), pantalla, 1)

            self.resAnterior = str(eval(pantalla))
            self.label.setText(str(eval(pantalla)))
        except:
            self.label.setText("SYNTAX ERROR")

    def calc_trig(self, numero, operacion):
        operaciones = {"sen": math.sin, "cos": math.cos, "tan": math.tan}
        return operaciones[operacion](float(numero))
        
    # ------------------- Fin Funciones Calculadora -------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculadora"))
        self.label.setText(_translate("MainWindow", "0"))
        self.uno.setText(_translate("MainWindow", "1"))
        self.cinco.setText(_translate("MainWindow", "5"))
        self.tres.setText(_translate("MainWindow", "3"))
        self.seis.setText(_translate("MainWindow", "6"))
        self.dos.setText(_translate("MainWindow", "2"))
        self.siete.setText(_translate("MainWindow", "7"))
        self.cuatro.setText(_translate("MainWindow", "4"))
        self.cero.setText(_translate("MainWindow", "0"))
        self.ocho.setText(_translate("MainWindow", "8"))
        self.nueve.setText(_translate("MainWindow", "9"))
        self.masmenos.setText(_translate("MainWindow", "+  -"))
        self.punto.setText(_translate("MainWindow", "."))
        self.limpiar.setText(_translate("MainWindow", "AC"))
        self.parentesis_izq.setText(_translate("MainWindow", "("))
        self.igual.setText(_translate("MainWindow", "="))
        self.mas.setText(_translate("MainWindow", "+"))
        self.resta.setText(_translate("MainWindow", "-"))
        self.multi.setText(_translate("MainWindow", "*"))
        self.divi.setText(_translate("MainWindow", "/"))
        self.ans.setText(_translate("MainWindow", "ans"))
        self.seno.setText(_translate("MainWindow", "sen"))
        self.coseno.setText(_translate("MainWindow", "cos"))
        self.tangente.setText(_translate("MainWindow", "tan"))
        self.borrar.setText(_translate("MainWindow", "DEL"))
        self.parentesis_der.setText(_translate("MainWindow", ")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
